# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    com.wms: INFO

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/wms
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
  liquibase:
    contexts: dev
    change-log: classpath:/db/changelog/changelog-master.xml
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
server:
  port: 8081

wms:
  app:
    jwtSecret: lItEJsfEUhroEfiHuwAztdbopxfkHmNPEAKQRZtJ
    jwtExpirationMs: 86400000

