version: '2'
services:
  wms-frontend:
    image: registry.hub.docker.com/wms2022/wms:latest
    ports:
      - 8930:80
  wms-backend:
    image: registry.hub.docker.com/wms2022/wmsbackend:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=portainer
    ports:
      - 8931:8000
  wms-database:
    image: 'postgres:latest'
    expose:
      - 5432
    environment:
      POSTGRES_USER: root_wmS_mo_user
      POSTGRES_PASSWORD: root_wmS_mo_p@5sWord
      POSTGRES_DB: wms-database
    volumes:
      - ./db-data/:/var/lib/postgresql/data/